language: node_js
node_js:
  - 'node' # implies latest version

cache:
  directories:
    - node_modules
    - fullcalendar

before_script: bin/travis-before-script.sh
after_script: bin/travis-after-script.sh

script: npm run test
