language: node_js
node_js:
  - 'node' # implies latest version

cache:
  directories:
    - node_modules
    - fullcalendar

before_install: bin/travis-before-install.sh
before_script: bin/travis-before-script.sh
script: npm run test
